[build]
  command = "npm run build"
  publish = "web"

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
